### PR TITLE
Update which npm

### PR DESCRIPTION
**Pull request by watilde**
Fixes https://github.com/workshopper/how-to-npm/pull/17, https://github.com/workshopper/how-to-npm/pull/19 and https://github.com/workshopper/how-to-npm/pull/32. Could someone try this patch on Windows?

cc @workshopper/how-to-npm-leads

### CODE REVIEW

**Comment by watilde** [comment]
I'm not sure that I should replace that with just `npm`.

**Comment by emzinnia** [comment]
Just finished running through the tutorial on Windows 10 and didn't face any issues that would normally cause it to break due to the quotation marks.

LGTM 👍 😄

**Review by emzinnia — APPROVED** [review]

**Comment by watilde** [comment]
@EmmaRamirez Thanks for your review! I will 🐑  it then :)

**Comment by schellingerhout** [comment]
Just tested on windows 10 with npm installed at "C:\Program Files\nodejs\npm". Seems cause #56 again (See #57 for fix)

**Pull request merged**
